pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                echo 'Dependencies stage simulated for CI demo'
                bat 'echo Dependencies Installed'
            }
        }

        stage('Build') {
            steps {
                echo 'Checking Python Version...'
                bat '"D:\\Python\\python.exe" --version'
            }
        }

        stage('Test') {
    steps {
        echo 'Running Django Test Cases...'
        bat '"D:\\Python\\python.exe" manage.py test'
    }
}

        stage('Deploy') {
            steps {
                echo 'Deploying Application...'
                bat 'echo Deployment Successful'
            }
        }
    }
}
