pipeline {
    agent any

    stages {

       stage('Install Dependencies') {
    steps {
        echo 'Installing Python Dependencies...'
        bat '"D:\\Python\\python.exe" -m pip install --upgrade pip'
        bat '"D:\\Python\\python.exe" -m pip install -r iEPM-online-exams-master\\requirements.txt'
    }
}

        stage('Build') {
            steps {
                echo 'Checking Python Version...'
                bat '"D:\\Python\\python.exe" --version'
            }
        }

        stage('Test') {
            steps {
                echo 'Running Test Stage...'
                bat 'echo Test Successful'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying Application...'
                bat 'echo Deployment Successful'
            }
        }
    }
}
